version: "3.7"
services:
  nginx-backend:
    image: nginx:latest
    ports:
      - "8443:443" # Expose port 8443 on the host and map it to 443 on the container.
    volumes:
      - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf
      - /root/rewardflights.io.crt:/etc/nginx/certs/rewardflights.io.crt
      - /root/rewardflights.io.key:/etc/nginx/certs/rewardflights.io.key
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - DEPLOYMENT=api
      - LC_CTYPE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    env_file: .env.prod
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_BACKEND_URL: 'https://rewardflights.io:8443/api'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/rewardflights.io.crt:/etc/nginx/certs/rewardflights.io.crt:ro
      - /root/rewardflights.io.key:/etc/nginx/certs/rewardflights.io.key:ro
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  default:
    name: million_net
