version: "3.7"
services:
  backend:
    build:
      context: ./backend
    environment:
      - DEPLOYMENT=api
      - LC_CTYPE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    env_file: .env
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      args:
        REACT_APP_BACKEND_URL: 'http://170.64.192.200:8000'
    ports:
      - "80:80"
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  default:
    name: million_net
