# Generated by Django 4.2 on 2023-09-02 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitynotification',
            name='flight_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Economy', 'ECONOMY'), ('Premium Economy', 'PREMIUM_ECONOMY'), ('Business', 'BUSINESS'), ('First', 'FIRST')], max_length=20), default='Economy', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabilitynotification',
            name='preferred_programs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Virgin Velocity', 'VA'), ('Qantas FF', 'QF')], max_length=20), size=None),
        ),
    ]
