# Generated by Django 4.2 on 2023-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flightclassdetail_remaining_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightclassdetail',
            name='tax_per_adult',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
